#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get cw1-6005-pw6g08/location
feed="$RET"
db_get cw1-6005-pw6g08/number
num="$RET"

conf="`cat /etc/cw1-6005-pw6g08/global.conf`"
echo "$conf" | 
awk -v pat="$feed" '/^<feeds>/{p=1;print;print pat}/<\/feeds>/{p=0}!p' |
awk -v pat="$num" '/^<items>/{p=1;print;print pat}/<\/items>/{p=0}!p' > /etc/cw1-6005-pw6g08/global.conf


db_stop
